apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/danielsagie/project_conf
    targetRevision: HEAD
    path: k8s_conf
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true