name: argo-triger
on: 
   repository_dispatch:
    types: [Trigger Workflow]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v3
       